# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - new-angapp

# Controls when the action will run.
on:
  push:
    branches:
      - master
      - '40_stages/DEV/**'
      - '40_stages/QA/**'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      #check out the right version and branch that is associated with the GitHub push or pull request.
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./dist/angular-app-with-azure

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
      - name: BranchName
        run: |
          echo "Source Branch: ${{ github.ref_name }}"
      - name: 'Deploy to Dev'
        uses: azure/webapps-deploy@v2
        if:  ${{ startsWith( github.ref_name, '40_stages/DEV') }}
        env:
          PUBLISHPROFILE:  ${{ secrets.AZUREAPPSERVICE_DEV_PUBLISHPROFILE }}
          APP_NAME: "new-angapp-stageDev"
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ env.PUBLISHPROFILE }}
          package: .
      - name: 'Deploy to master'
        uses: azure/webapps-deploy@v2
        if:  ${{ startsWith( github.ref_name, 'master') }}
        env:
          PUBLISHPROFILE:  ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          APP_NAME: "new-angapp"
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ env.PUBLISHPROFILE }}
          package: .
